# render.yaml
services:
  - type: web
    name: health-monitor-app
    runtime: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
